<?php if($this->isNoticeEnabled()): ?>
<script type="text/javascript">
var $buoop = {<?php echo $this->getJsOptions(); ?>} 
$buoop.ol = window.onload; 
window.onload=function(){ 
 try {if ($buoop.ol) $buoop.ol();}catch (e) {} 
 var e = document.createElement("script"); 
 e.setAttribute("type", "text/javascript"); 
 e.setAttribute("src", "//browser-update.org/update.js"); 
 document.body.appendChild(e); 
} 
</script> 
<?php endif; ?>
