<?php
class Artis_Salesforceconnect_IndexController extends Mage_Core_Controller_Front_Action
{
    public function indexAction()
    {
	
	
	if($this->getRequest()->getParam('sf_sub')!="")
	{
	    $uname=$this->getRequest()->getParam('uname');

	    $pass=$this->getRequest()->getParam('pass');

	    $SECURITY_TOKEN="FFht9JEnPWXcQZBMEkWvFG3A";
	    
	    
	    $base_path=Mage::getBaseDir('base');
		
 
	    require_once ($base_path.'/salesforce/soapclient/SforcePartnerClient.php');

		
	
		try{
			  //the save the data and send the new account email.
			  $mySforceConnection = new SforcePartnerClient();
			  $aaa=$mySforceConnection->createConnection($base_path."/salesforce/soapclient/partner.wsdl.xml");


			  $log=$mySforceConnection->login("rudra@mmr.com.au", "option123");

			$query = "SELECT Id, FirstName, LastName, Phone from Contact";
			$response = $mySforceConnection->query($query);

			$ids=array();
			//echo "Results of query '$query'<br/><br/>\n";
			foreach ($response->records as $record) {
			    // Id is on the $record, but other fields are accessed via the fields object
			    /*echo $record->Id[0] . ": " . $record->fields->FirstName . " "
				. $record->fields->LastName . " " . $record->fields->Phone . "<br/>\n";*/
				array_push($ids, $record->Id[0]);

			}



			// $ids is an array of record ids built in the previous step
			$response = $mySforceConnection->retrieve('Id, Email, FirstName, LastName, Phone',
				'Contact', $ids);


			$arr_email=array();
			$arr_fname=array();
			$arr_lname=array();
			foreach ($response as $record) {
			    //echo $record->Password; //. ": " . $record->fields->FirstName . " "
			    //. $record->fields->LastName . " " . $record->fields->Phone . "<br/>\n";
				$arr_email[]=$record->Email;
				$arr_fname[]=$record->fields->FirstName;	
				$arr_lname[]=$record->fields->LastName;		
			}
			//exit;
			if(array_search($uname,$arr_email)!=false)
			{
				$array_key=array_search($uname,$arr_email);	
			}
			else
			{
				Mage::getSingleton('core/session')->addError("Invalid SF user");
				$url = Mage::getBaseUrl();
			    	Mage::app()->getResponse()->setRedirect($url);
			   	Mage::app()->getResponse()->sendResponse();
				exit;
			}

		}

		catch(Exception $ex){
			// echo 'Caught exception: ',  $ex->getMessage(), "\n";

			Mage::getSingleton('core/session')->addError($ex->getMessage());
			$url = Mage::getBaseUrl();
		    	Mage::app()->getResponse()->setRedirect($url);
		   	Mage::app()->getResponse()->sendResponse();
			exit;
			
	               
		} 
		
	

	    $full_name=$log->userInfo->userFullName;

	    $arr_f_l_name=array();
	
	    $arr_f_l_name=explode(" ", $full_name);

    	    /*$fname=$arr_f_l_name[0];
    	    $lname=$arr_f_l_name[1];*/
	    $fname=$arr_fname[$array_key];
	    $lname=$arr_lname[$array_key];

	    //$user_email=$log->userInfo->userEmail;	
	    $user_email=$arr_email[$array_key];
	    //$user_name=$log->userInfo->userName;


	   	$customer_email = $user_email;  // email adress that will pass by the questionaire 
		$customer_fname = $fname;      // we can set a tempory firstname here 
		$customer_lname = $lname;       // we can set a tempory lastname here 
		$passwordLength = 10;                    // the lenght of autogenerated password

		$customer = Mage::getModel('customer/customer');
		$customer->setWebsiteId(Mage::app()->getWebsite()->getId());
		$customer->loadByEmail($customer_email);
		/*
		* Check if the email exist on the system.
		* If YES,  it will not create a user account. 
		*/

		if(!$customer->getId()) {

		   //setting data such as email, firstname, lastname, and password 

		  $customer->setEmail($customer_email); 
		  $customer->setFirstname($customer_fname);
		  $customer->setLastname($customer_lname);
		  $pass=$customer->generatePassword($passwordLength);
		  $customer->setPassword($pass);

		  	try{
			  //the save the data and send the new account email.
			  $customer->save();
			  $customer->setConfirmation(null);
			  $customer->save(); 
			  $customer->sendNewAccountEmail();
			}

			catch(Exception $ex){

			} 

		}
		
		$customer->setData("group_id",2);
		$customer->save();

		  $email = $customer_email;
		  $customer = Mage::getModel('customer/customer');
		  $customer->setWebsiteId(Mage::app()->getWebsite()->getId());
		  $customer->loadByEmail(trim($email));
		  Mage::getSingleton('customer/session')->loginById($customer->getId());

		 $url = Mage::getBaseUrl();
                 $this->_redirectUrl($url);

	}


	  

			
		$this->loadLayout();     
		$this->renderLayout();
    }
}
